name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build backend
        run: dotnet build

      - name: Run backend tests
        run: dotnet test

      - name: Build frontend
        run: |
          cd DotnetTemplate.Web
          npm install
          npm run build

      - name: Run frontend tests
        run: npm t
